apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.svc.type }}
  ports:
  - port: {{ .Values.svc.port }}
    targetPort: {{ .Values.svc.port }}
    protocol: TCP
    name: {{ .Values.svc.name }}
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    slot: {{ .Values.productionSlot }}
