apiVersion: v1
data:
  logging-activity-tracker.conf: |
    <source>
      type tail
      path /var/log/at/*.log
      exclude_path /var/log/at/*.gz
      pos_file /mnt/ibm-kube-fluentd-persist/fluentd-at.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag kubernetes.at.*
      format json
      read_from_head true
      read_lines_limit 100
      rotate_wait 43200 # set to 12 hours in case AT gets behind in reading events
    </source>
    <match kubernetes.at.**>
      type ibmactivitytracker
      targetHost activity-tracker.ng.bluemix.net
      service_region ng
      ibm_plugin_log_level warn
      flush_interval 10s
      buffer_queue_full_action exception
      buffer_queue_limit 10
      buffer_chunk_limit 2m
      buffer_type file
      buffer_path /mnt/ibm-kube-fluentd-persist/fluentd-at-buffer.buf
      secrets_path /mnt/activity-tracker/secrets
      retry_wait 1s
      max_retry_wait 10s
      disable_retry_limit true
    </match>
kind: ConfigMap
metadata:
  name: at-fluentd-config
  namespace: kube-system