# broker secret
apiVersion: v1
data:
  user: {{ .Values.svc.user | b64enc }}
  pass: {{ .Values.svc.pass | b64enc }}
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: "{{ .Values.svc.name }}"
  namespace: {{ .Values.namespace }}
type: Opaque
---

# provider secret
apiVersion: v1
data:
  apikey: {{ .Values.provider.apikey | b64enc }}
  endpoint: {{ .Values.provider.endpoint | b64enc }}
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: "{{ .Values.provider.secret }}"
  namespace: {{ .Values.namespace }}
type: Opaque
---
