# Tomcat Deployment file example. Be sure to modify the "image:" link address to fit your enviroment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: YOUR_REGISTRY_ADDRESS_LINK/YOUR_SPACE/tomcat:latest
        ports:
        - containerPort: 80
