---
{{ if .Values.blue.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue-blue
  labels:
    name: catalogue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: catalogue
        slot: blue
    spec:
      containers:
      - name: catalogue-blue
        image: {{ .Values.registry }}/{{ .Values.catalogue.image }}:{{ .Values.catalogue.tag }}
        imagePullPolicy: Always
        {{- if .Values.zipkin.enabled }}
        env:
         - name: ZIPKIN
           value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
{{ end }}
