---
{{ if .Values.blue.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue-db-blue
  labels:
    name: catalogue-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: catalogue-db
        slot: blue
    spec:
      containers:
      - name: catalogue-db-blue
        image: {{ .Values.registry }}/{{ .Values.cataloguedb.image }}:{{ .Values.cataloguedb.tag }}
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          - name: MYSQL_DATABASE
            value: socksdb
        ports:
        - name: mysql
          containerPort: 3306
{{ end }}
