apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: hdngo@us.ibm.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
