---
{{ if .Values.green.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: session-db-green
  labels:
    name: session-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: session-db
        slot: green
    spec:
      containers:
      - name: session-db-green
        image: redis:alpine
        imagePullPolicy: Always
        ports:
        - name: redis
          containerPort: 6379
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
{{ end }}
