---
{{ if .Values.blue.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-db-blue
  labels:
    name: user-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-db
        slot: blue
    spec:
      containers:
      - name: user-db-blue
        image: {{ .Values.registry }}/{{ .Values.userdb.image }}:{{ .Values.userdb.tag }}
        imagePullPolicy: Always
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
{{ end }}
