---
{{ if .Values.green.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-green
  labels:
    name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user
        slot: green
    spec:
      containers:
      - name: user-green
        image: {{ .Values.registry }}/{{ .Values.user.image }}:{{ .Values.user.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: user-db:27017
        {{- if .Values.zipkin.enabled }}
        - name: ZIPKIN
          value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
{{ end }}
