{{ if .Values.blue.enabled }}
{{ if .Values.zipkin.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-mysql-blue
  labels:
    name: zipkin-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zipkin-mysql
        slot: blue
    spec:
      containers:
      - name: zipkin-mysql-blue
        image: openzipkin/zipkin-mysql:1.20.0
        imagePullPolicy: Always
        ports:
        - name: mysql
          containerPort: 3306
{{ end }}
{{ end }}
