{{- if .Values.zipkin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: zipkin-stage
  labels:
    name: zipkin
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 9411
    targetPort: 9411
    nodePort: 30002
  selector:
    name: zipkin
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
{{- end -}}
