{{- if .Values.zipkin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: zipkin-mysql-stage
  labels:
    name: zipkin-mysql
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    name: zipkin-mysql
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
{{- end -}}
