{{ if .Values.blue.enabled }}
{{- if .Values.zipkin.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-cron-blue
  labels:
    name: zipkin-cron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zipkin-cron
        slot: blue
    spec:
      containers:
      - name: zipkin-cron-blue
        image: openzipkin/zipkin-dependencies:1.4.0
        imagePullPolicy: Always
        env:
        - name: STORAGE_TYPE
          value: mysql
        - name: MYSQL_HOST
          value: zipkin-mysql
        - name: MYSQL_USER
          value: zipkin
        - name: MYSQL_PASS
          value: zipkin
        command: ["crond"]
        args: ["-f"]
{{- end -}}
{{ end }}
